module.exports = {
  SET_MAX_CACHE_SIZE: "SET_MAX_CACHE_SIZE",
  SET_MAX_TILES: "SET_MAX_TILES",
  SET_TIMEOUT: "SET_TIMEOUT",
  REQUEST_TILE: "REQUEST_TILE",
  CREATED_TILE: "CREATED_TILE",
  CREATE_TILE_ERROR: "CREATE_TILE_ERROR",
  CLEAR_CACHE: "CLEAR_CACHE"
};
